version: '3.8'

services:
  php:
    image: php:7.4-cli
    container_name: php-websocket-server
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - "8080:8080" # Exposing port 8080 for the WebSocket server
    depends_on:
      - redis
    command: >
      bash -c "
        php -S 0.0.0.0:8080 -t /var/www &&
        tail -f /dev/null
      "

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  app:
